version: "2.4"
services:
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - ./sql-data/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Admin123